### ISSUE TITLE
Router match method always returns false

### ISSUE THREAD

**Issue by blrobin2** [mlaphp/mlaphp#1]
On line 229, there is a check whether the path on the file matches the file path, but it seems to strip away too much of the path to check, as when I stepped through it, it ended up comparing '/' to the actual path, which of course is false. I'm not sure if I'm not defining my path correctly (it seems to look fine right up to this point), but I can remove that check and everything works fine.

I'm working on a WAMP setup right now, so I don't know if that affects things or not...

**Comment by pmjones** [comment]
Are you still seeing the problem? If so, let me know if you can identify a fix.

**Comment by redbeardcreator** [comment]
On a Windows set up, the tendency would be to describe local paths with back slashes (`\`) instead of forward slashes (`/`) the Unix-descended world uses. So, without seeing how @blrobin2 is using `Router`, I'd guess the problem is in the constructor, which calls `rtrim($pages_dir, '/')`, which would not act correctly if a Windows-style path is passed in.

**Comment by blrobin2** [comment]
I'm setting up the router like so:
$di->set('router', function () use ($di) {
    $router = new Mlaphp\Router('../pages/');
    $router->setRoutes(include 'routes.php');

```
return $router;
```

}); 

And then matching paths like so:
$router = $di->get('router');

//matches against the url path
$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$route = $router->match($path);

//If a route exists
if($di->has($route)) {
    //create a new controller instance
    $controller = $di->newInstance($route);
} else {
    //Call not found controller
    $controller = $di->newInstance('Controller\Not-Found');
}

I hope this helps.

**Comment by redbeardcreator** [comment]
I don't know if this applies to you, but what is the host-relative URI your app lives at? For example `http://example.com/my/app/` would give a host-relative URI of `my/app`. If it doesn't live at the root, you have to call `$router->setFront('my/app');` In your example, it would look like:

``` php
$di->set('router', function () use ($di) {
    $router = new Mlaphp\Router('../pages/');
    $router->setRoutes(include 'routes.php');
    $router->setFront('my/app');
    return $router;
});
```

**Comment by pmjones** [comment]
Are we stil seeing trouble with this?

**Comment by blrobin2** [comment]
I have not had the opportunity to check. I'm afraid it would be some time
before I could look into it again. Feel free to close this and if I run
into an issue again, I'll get in touch. I'm sorry I can't do more. Thank
you for looking into it!
