### ISSUE TITLE
Request variable not populated in request class

### ISSUE THREAD

**Issue by MarkNBroadhead** [mlaphp/mlaphp#3]
The request variable is not being set from $globals['_REQUEST'] when the php setting auto_globals_jit is set to its default of On.

To reproduce, run the example code once as is. To fix it, uncomment the 2nd and 3rd commented lines.
Example code:

```
<?php
require_once '/vendor/autoload.php';
$request = new \Mlaphp\Request($GLOBALS);
?>
<!DOCTYPE>
<html>
<head>
    <title>MLAPHP Request->Request test</title>
</head>
<body>
    <h1>Superglobals</h1>
    <h2>Printed out with \$_GET</h2>
    <?php print_r($_GET); ?>

    <h2>Printed out with \$_POST</h2>
    <?php print_r($_POST); ?>

    <!-- When the next two lines are commented out, $request->request doesn't work.-->
    <!--<h2>Printed out with \$_REQUEST</h2>-->
    <?php //print_r($_REQUEST); ?>
    <h1>MLAPHP\Request object</h1>
    <h2>Printed out with \$request->get</h2>
    <?php print_r($request->get); ?>

    <h2>Printed out with \$request->post</h2>
    <?php print_r($request->post); ?>

    <h2>Printed out with \$request->request</h2>
    <?php print_r($request->request); ?>
</body>
</html>
```

Possible Solutions:
- Change the auto_globals_jit setting in php.ini from the default "On" to "Off".
- Add a reference to $_REQUEST on line 94 of Request.php, or modify the class in some other way.
- Re-create the Request object in a file directly accessing the $_REQUEST object.

**Comment by pmjones** [comment]
@MarkNBroadhead Ah, good catch.  I recall the JIT stuff being trouble in Aura.Web as well. The solution there was to inject each individual superglobal, but I'd like to avoid that here (and thus avoid breaking BC).

If you could, do me a favor and try the following. In the __construct() method, add the line `$$superglobal;` just inside the foreach() loop. It should look something like this afterwards:

```
    foreach ($properties as $property => $superglobal) {
        $$superglobal;
        if (isset($globals[$superglobal])) {
            $this->$property = $globals[$superglobal];
        }
    }
```

My guess is that will be enough to invoke the JIT logic, _and_ allow you to inject whatever $globals array you want for testing.

If that works, send a PR so you get some credit.

Thanks!

**Comment by MarkNBroadhead** [comment]
Yeah, I'll get to that when I have a chance. Thanks for the suggestion.

**Comment by pmjones** [comment]
Nope, $$superglobal does not do the trick. You have to mention the exact superglobal by name directly. I'll do so in the constructor.
