### ISSUE TITLE
Accessing $post via magic method

### ISSUE THREAD

**Issue by MarkNBroadhead** [mlaphp/mlaphp#4]
When accessing the post variable in the Request class, I get a warning regarding accessing the variable via magic method because the referenced field is not found in the subject class. This is due to the variable being created in the constructor and is not explicitly created like all the other superglobals.

**Comment by MarkNBroadhead** [comment]
Will submit pull request later today or tomorrow.

**Comment by MarkNBroadhead** [comment]
Pull request issued https://github.com/mlaphp/mlaphp/pull/5

**Comment by neyl** [comment]
Please fix this. I just started using Request in my app only to discover in horror that the post property is missing. Until I realized that php allows to create the property dynamically so it is 'working' but still might have some side effects - e.g. accessing $request->post when $_POST is not defined e.g. maybe in cli.

On another note, cannot thank you enough for the book - +1000

**Comment by pmjones** [comment]
Applied #5. Thanks for the fix!

**Comment by pmjones** [comment]
> cannot thank you enough for the book - +1000

Thanks @neyl :-)
