### ISSUE TITLE
Is the information in the book and this code still valid?

### ISSUE THREAD

**Issue by simplexx** [mlaphp/mlaphp#7]
Hi, I am currently reading your book, and was wondering if the information in it, and the code in this repo is still valid. I really like how the book is written (simple and clean, but loaded with essential information). I am asking because the book is a few years old already (and mentions php 5.x etc.), and it would be nice to know if the info inside can still be trusted, or if it is outdated.

I got the book for free to check if it is useful for me, and if I can use the info in it for the legacy application I am working on, I will buy it.

Cheers

**Comment by pmjones** [comment]
Hi @simplexx --

Yes, everything in it should still be valid. Version numbers and other minor details may change over time, but the techniques, principles, and process are timeless.

Let me know how your modernization work goes!

-- pmj

**Comment by simplexx** [comment]
Hi @pmjones 

Awesome! just bought it.

The modernization goes well so far, but I have a bit of an issue with chapter 5. (Replace global With Dependency Injection). If you don't mind, I have a quick question:

Each of my classes is basically a collection of functions, some using properties to save reusable data. Some of these classes are massive (some depend on 20+ other classes, because other classes are used inside one or a few functions). Dependency injection currently is not possible, because of circular dependencies (class A has a function which uses class B, and vice versa). This happens a LOT.

Classes are loaded to global scope and used when needed (one instance per class max.).

In my current situation, it is simply not viable to refactor all classes to support dependency injection (split classes, remove circular dependencies etc.), because It is impossible to do it one class at a time due to the massive amount of circular dependencies. It would require massive refactoring of many classes at the same time first (without tests...).

In order to be able to implement testing as fast as possible, my plan is the following: Instead of using dependency injection, I will use a service locator. In the class constructor I get the instances of the classes I need and save them as private properties, sth. like this:

class User 
{
    private $database = null;
    private ...

    public function __construct() {
        //instantiate ServiceLocator
        $serviceLocator = ServiceLocator::getInstance();
    
        //load all needed classes 
        $this->database = $serviceLocator.get('DatabaseClass');
        ...
    }
...
}

This certainly is not optimal, but I could add this in a few days and get rid of all global classes. Then I could start adding some basic tests, and then gradually refactor and split the big classes, remove circular dependencies etc. 

Is this plan ok, and will it allow for some basic automated testing?

Cheers!

**Comment by thunderrabbit** [comment]
HI Paul @pmjones 

Though the ideas are timeless and the book has helped me a lot, I haven't been able to get the \Request class to work because PHP 8.1 no longer allows referencing $_GLOBALS.   Have you found a workaround for this?

**Comment by pmjones** [comment]
@thunderrabbit, @Windtalk3r:

> PHP 8.1 no longer allows referencing $_GLOBALS

Oh **man** -- that's a doozy. No, have not had to deal with it. I can think of two things:

1. Consider using [Sapien](http://sapienphp.com) as an alternative, but that takes you away from the book, and does not deal with $_SESSION the way \Request does here.
2. Meanwhile, I will try to work up the smallest possible an update to \Request that works from PHP 8.1 back through PHP 5.x (probably 5.6), *or* create a Request81 class specifically for PHP 8.1 and later.

Thanks for bringing it to my attention!

**Comment by pmjones** [comment]
@simplexx Very sorry to take so so so long to reply -- don't know why I did not see your followup.

>  I will use a service locator ... Is this plan ok, and will it allow for some basic automated testing?

You have probably figured it out already, but the answer is "yes" -- a Service Locator can be reasonable, and moves you toward an inversion-of-control regime. It's not as great as DI but it is definitely better than globals proper.

**Comment by pmjones** [comment]
@thunderrabbit et al: please review #8 and the `Request81` class therein as an updated alternative to the original `Request` object; let me know how well it works for you. I have done minimal testing here; it works as far back as PHP 5.6, and *should* work for 8.1 and later.

**Comment by thunderrabbit** [comment]
Thank you so much Paul!

Your new Request81.php is working perfectly for me as a drop in replacement for Request.php in my project.  
I'm on Ubuntu 22 with PHP 8.1

**Comment by pmjones** [comment]
Fixed by #8
